import type { CVAnalysisPdfInput } from '@agentrepo/application';
import {
  Document,
  type DocumentProps,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer';
import { createElement as h, type ReactElement } from 'react';

// Corporate palette (mirrors the web design tokens).
const COLORS = {
  ink: '#1b1714',
  accent: '#7a2230',
  muted: '#8d8273',
  paper: '#fdf8ef',
  line: '#e5dccb',
};

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: COLORS.paper,
    color: COLORS.ink,
    fontSize: 10,
    padding: 32,
    fontFamily: 'Helvetica',
  },
  sidebar: {
    width: '34%',
    paddingRight: 18,
    borderRightWidth: 1,
    borderRightColor: COLORS.line,
  },
  main: { width: '66%', paddingLeft: 18 },
  name: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: COLORS.accent },
  role: { fontSize: 11, color: COLORS.muted, marginTop: 2, marginBottom: 14 },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.accent,
    marginTop: 12,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  item: { marginBottom: 3, lineHeight: 1.4 },
  paragraph: { marginBottom: 8, lineHeight: 1.5 },
  metaBox: {
    backgroundColor: '#f4ecdd',
    borderRadius: 4,
    padding: 8,
    marginBottom: 12,
  },
  metaLabel: { fontSize: 8, color: COLORS.muted, textTransform: 'uppercase' },
  metaValue: { fontSize: 10, marginTop: 2 },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 32,
    right: 32,
    fontSize: 8,
    color: COLORS.muted,
    textAlign: 'center',
  },
});

const PROFILE = {
  name: 'Luis BZ',
  role: 'AI Engineer · agentrepo.dev',
  skills: [
    'LLM orchestration (LangChain, DeepSeek)',
    'TypeScript · Node.js · NestJS',
    'Next.js · React · tRPC',
    'Hexagonal architecture & DDD',
    'PostgreSQL · Prisma · Supabase',
    'CI/CD · Nx monorepos',
  ],
  experience: [
    'Founder & builder of agentrepo.dev — open hub for AI agents and skills',
    'AI-driven product workflows: contact triage, PDF reporting, email agents',
    'Full-stack platform engineering across web, admin and AI backends',
  ],
  education: ['Software Engineering', 'Continuous ML/AI specialisation'],
};

function section(title: string, children: ReactElement[]): ReactElement {
  return h(View, {}, h(Text, { style: styles.sectionTitle }, title), ...children);
}

function textItems(items: string[]): ReactElement[] {
  return items.map((item, index) =>
    h(Text, { key: index, style: styles.item }, `• ${item}`)
  );
}

function analysisParagraphs(analysis: string): ReactElement[] {
  return analysis
    .split(/\n{2,}/)
    .filter((block) => block.trim().length > 0)
    .map((block, index) =>
      h(Text, { key: index, style: styles.paragraph }, block.trim())
    );
}

export function buildCvAnalysisDocument(
  input: CVAnalysisPdfInput
): ReactElement<DocumentProps> {
  return h(
    Document,
    { title: 'Luis BZ — Profile & AI Analysis' },
    h(
      Page,
      { size: 'A4', style: styles.page },
      h(
        View,
        { style: styles.sidebar },
        h(Text, { style: styles.name }, PROFILE.name),
        h(Text, { style: styles.role }, PROFILE.role),
        section('Skills', textItems(PROFILE.skills)),
        section('Experience', textItems(PROFILE.experience)),
        section('Education', textItems(PROFILE.education))
      ),
      h(
        View,
        { style: styles.main },
        h(
          View,
          { style: styles.metaBox },
          h(Text, { style: styles.metaLabel }, 'Prepared for'),
          h(Text, { style: styles.metaValue }, input.recipientName),
          h(Text, { style: { ...styles.metaLabel, marginTop: 6 } }, 'Topic'),
          h(Text, { style: styles.metaValue }, input.subject)
        ),
        h(Text, { style: styles.sectionTitle }, 'Personalised analysis'),
        ...analysisParagraphs(input.aiAnalysisText)
      ),
      h(
        Text,
        { style: styles.footer, fixed: true },
        'Generated by the agentrepo.dev AI contact agent'
      )
    )
  );
}
